spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:universe.db
  jpa:
    database-platform: com.starwars.millenniumfalcononboardcomputer.configuration.SQLiteDialect
    hibernate.ddl-auto: update
  cors:
    allowed-origins: "*"

logging:
  level:
    root: OFF
